# Generated by Django 4.0.3 on 2022-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cv_pictures/'),
        ),
    ]
